# Textos do site do Pop3D nos três idiomas. Tom: mágico, leve e honesto (nada de "a IA roda no seu PC":
# a mágica acontece no seu computador). Os {{nomes}} do modelo.html vêm daqui.

PT = {
    "html_lang": "pt-BR",
    "titulo": "Pop3D: tudo o que você vê, agora em 3D no seu óculos VR",
    "descricao": "Filmes, séries, viagens, fotos da família, YouTube e jogos: o Pop3D transforma tudo o que passa no seu computador em 3D de verdade no seu óculos VR. Grátis.",
    "nav_magica": "A mágica", "nav_onde": "Onde funciona", "nav_duvidas": "Dúvidas", "nav_baixar": "Baixar grátis",
    "selo": "<b>Grátis</b> · Meta Quest e óculos de PC",
    "h1": "Tudo o que você vê,<br><span class=\"grad\">agora em 3D.</span>",
    "lead": "Filmes, séries, a viagem do ano passado, o aniversário da família, o YouTube, seus jogos. O Pop3D transforma tudo o que passa no seu computador em 3D de verdade, direto no seu óculos VR. Na hora, sem converter nada.",
    "baixar": "Baixar grátis para Windows", "ver_magica": "Ver a mágica",
    "rotulo_heroi": "Big Buck Bunny · Blender Foundation",
    "alt_heroi": "Cena do filme Big Buck Bunny com profundidade: a flecha sai da tela",
    "magica_olho": "A mágica por dentro",
    "magica_h2": "Cada imagem vira um mundo em camadas.",
    "hist1": "<b>Uma imagem comum.</b> Plana, como qualquer vídeo na sua tela.",
    "hist2": "<b>O Pop3D enxerga a distância</b> de cada ponto, do focinho do personagem à última árvore.",
    "hist3": "<b>Separa a cena em camadas</b> e imagina o que estava escondido atrás de cada uma.",
    "hist4": "<b>Remonta tudo em 3D</b>, uma imagem para cada olho. O seu cérebro faz o resto.",
    "alt_historia": "Cena do filme Big Buck Bunny separada em camadas de profundidade",
    "num1_v": "Grátis", "num1_t": "Sem anúncio, sem assinatura e sem pegadinha.",
    "num2_v": "Na hora", "num2_t": "Deu play, já está em 3D. Nada de converter vídeo.",
    "num3_v": "Só seu", "num3_t": "Seus vídeos nunca saem do seu computador.",
    "tudo_olho": "Não é só filme",
    "tudo_h2": "Passou no seu PC? Vira 3D.",
    "tudo_intro": "Filmes são só o começo. Viagens, momentos em família, fotos, vídeos do YouTube e até o seu jogo favorito ganham profundidade.",
    "c_filme": "Filmes e séries", "c_filme_p": "Sua coleção inteira em 3D, numa tela de cinema só sua.",
    "c_jogo": "Jogos", "c_jogo_p": "Seus jogos de PC em 3D no óculos, sem instalar mod nenhum.",
    "c_viagem": "Viagens", "c_viagem_p": "Volte para aquela praia. Desta vez, com profundidade.",
    "c_familia": "Família", "c_familia_p": "Aniversários, formaturas, o primeiro passo do bebê.",
    "c_fotos": "Fotos", "c_fotos_p": "Abra uma foto no PC e entre nela.",
    "c_youtube": "YouTube e navegador", "c_youtube_p": "Vlogs, documentários, clipes: o que estiver na tela do computador.",
    "c_natureza": "Natureza", "c_natureza_p": "Paisagens com a profundidade que elas têm de verdade.",
    "dif_olho": "Veja a diferença",
    "dif_h2": "A mesma imagem. Outra dimensão.",
    "dif_intro": "Arraste a linha. De um lado, a tela plana de sempre. Do outro, a mesma cena com o Pop3D. No óculos é ainda mais impressionante: cada olho recebe a sua própria imagem.",
    "dif_esq": "Tela comum", "dif_dir": "Com Pop3D", "dif_alt": "Comparação entre a imagem plana e a imagem com profundidade",
    "onde_olho": "Funciona com o que você já tem",
    "onde_h2": "Do seu jeito, no seu óculos.",
    "onde_intro": "Use o nosso app para o Quest, o jeito mais fácil, ou o programa de PC VR que você já usa.",
    "quest_selo": "Recomendado", "quest_h3": "App Pop3D para Meta Quest",
    "quest_p": "Abra o app no óculos e ele encontra o seu computador sozinho, pelo Wi-Fi de casa. Sem cabo e sem configurar nada.",
    "quest_l1": "Sem fio, pelo Wi-Fi", "quest_l2": "Encontra o PC sozinho", "quest_l3": "Menus feitos para o óculos", "quest_l4": "Grátis",
    "botao_quest": "App para Meta Quest", "detalhe_pc": "Windows 10 / 11 · NVIDIA RTX · Grátis",
    "em_breve_loja": "Em breve na Meta Horizon Store", "quest_ja": "Instalar agora pelo modo desenvolvedor",
    "baixar_olho": "Baixar", "baixar_h2": "Comece em poucos minutos.",
    "baixar_intro": "O Pop3D faz a mágica no computador e mostra no seu óculos. Instale no PC primeiro; o app do Quest é o jeito mais fácil de assistir.",
    "etapa_pc": "No computador", "pc_h3": "Pop3D para Windows",
    "pc_p": "Baixe, clique em Avançar e pronto. Ele se prepara sozinho para a sua placa de vídeo e se atualiza sozinho depois.",
    "obrigado": "<b>O download começou.</b> Abra o <b>Pop3D_Instalador.exe</b>. Se o Windows mostrar “O Windows protegeu o seu computador”, clique em <b>Mais informações</b> e depois em <b>Executar assim mesmo</b>.",
    "etapa_quest": "No Meta Quest",
    "dev_intro": "Enquanto o app não chega à loja, você já pode instalar pelo cabo USB:",
    "dev1": "No celular, abra o app <b>Meta Horizon</b> e ligue o <b>Modo de desenvolvedor</b> em Dispositivos › Configurações do headset. A Meta pede uma conta de desenvolvedor, que é grátis.",
    "dev2": "Ligue o Quest no computador com um cabo USB.",
    "dev3": "No Pop3D do computador, abra <b>Ajustes › Óculos</b>, clique em <b>Instalar no Quest</b> e toque em <b>Permitir</b> dentro do óculos. Pronto!",
    "dev_apk": "Já usa o SideQuest? Baixe o APK",
    "outros_h3": "Também funciona com",
    "outros_p": "Prefere o que já usa? O Pop3D conversa com os principais jeitos de ligar o óculos ao PC.",
    "steamvr_p": "Valve Index, HTC Vive, Pico e outros",
    "req_h2": "O que você precisa",
    "req_intro": "Um computador com placa de vídeo NVIDIA RTX e um óculos VR. Só isso.",
    "req_sistema": "Sistema", "req_placa": "Placa de vídeo", "req_espaco": "Espaço livre", "req_espaco_nota": "O app ocupa uns 9 GB; o resto é folga para instalar.", "req_oculos": "Óculos",
    "req_oculos_v": "Meta Quest 2, 3, 3S ou Pro, ou óculos de PC (SteamVR)",
    "duvidas_h2": "Dúvidas",
    "faq": [
        ("É grátis mesmo?", "Sim. Sem propaganda, sem assinatura e sem pegadinha."),
        ("Preciso converter os vídeos antes?", "Não. É só dar play: o 3D acontece enquanto você assiste."),
        ("Preciso instalar alguma coisa no óculos?", "Não é obrigatório. O app Pop3D para Quest é o jeito mais fácil: chega em breve à loja da Meta, e já dá para <a href=\"#baixar-quest\">instalar pelo modo desenvolvedor</a>. Se preferir, o Pop3D também funciona com Steam Link, Air Link, Virtual Desktop e SteamVR."),
        ("Instalei só o app no Quest. E agora?", "O app do Quest mostra o que o Pop3D do computador prepara. Instale também o <a href=\"#baixar\">Pop3D no seu PC com Windows</a>: com os dois abertos, o óculos encontra o computador sozinho."),
        ("A instalação é rápida?", "Na primeira vez, o Pop3D baixa cerca de 4 GB: é a inteligência artificial que faz a mágica acontecer, e ela já fica pronta para a sua placa de vídeo. O tempo depende da sua internet. Depois disso, o app abre em segundos e se atualiza sozinho."),
        ("Funciona com streaming?", "Funciona com o que aparece na tela do seu computador, como o YouTube e a maioria dos sites. Alguns serviços pagos protegem o vídeo contra cópia e não deixam nenhum programa capturar a imagem. Vídeos do seu computador funcionam direto."),
        ("Funciona sem placa NVIDIA?", "Por enquanto, a mágica precisa de uma placa de vídeo NVIDIA RTX. Se o seu PC não tiver, o instalador avisa logo no começo, antes de baixar qualquer coisa."),
        ("Meus vídeos saem do meu computador?", "Nunca. Tudo acontece no seu computador e o vídeo vai direto para o óculos pela sua rede de casa. O Pop3D envia só estatísticas anônimas de uso para ficar cada vez melhor, e dá para desligar nos Ajustes. Veja a <a href=\"{{url_privacidade}}\">Política de Privacidade</a>."),
        ("O Windows mostrou “O Windows protegeu o seu computador”. E agora?", "É o aviso padrão do Windows para programas novos, que a Microsoft ainda não conhece. Clique em <b>Mais informações</b> e depois em <b>Executar assim mesmo</b>."),
        ("Tive uma ideia para o Pop3D!", "Que ótimo! Dentro do app, em <b>Ideias e sugestões</b>, você manda direto para a gente. O Pop3D é novinho e cresce junto com quem usa."),
    ],
    "final_h2": "Pronto para ver tudo em <span class=\"grad\">3D</span>?",
    "final_p": "Grátis. Se instala sozinho. Funciona no seu óculos.",
    "privacidade": "Política de Privacidade", "versoes": "Todas as versões", "problema": "Achou um problema? Conta pra gente",
    "creditos_tit": "Créditos das imagens",
    "js": {"em_breve": "Em breve", "forno": "A primeira versão está saindo do forno.", "versao": "Versão",
           "no_pc": "Baixe no computador (Windows): o Pop3D roda no PC."},
}

EN = {
    "html_lang": "en",
    "titulo": "Pop3D: everything you watch, now in 3D on your VR headset",
    "descricao": "Movies, shows, travel videos, family photos, YouTube and games: Pop3D turns everything on your computer into real 3D on your VR headset. Free.",
    "nav_magica": "The magic", "nav_onde": "Where it works", "nav_duvidas": "FAQ", "nav_baixar": "Free download",
    "selo": "<b>Free</b> · Meta Quest and PC VR headsets",
    "h1": "Everything you watch,<br><span class=\"grad\">now in 3D.</span>",
    "lead": "Movies, shows, last year's trip, the family birthday, YouTube, your games. Pop3D turns everything on your computer into real 3D, right on your VR headset. Instantly, with nothing to convert.",
    "baixar": "Free download for Windows", "ver_magica": "See the magic",
    "rotulo_heroi": "Big Buck Bunny · Blender Foundation",
    "alt_heroi": "Scene from Big Buck Bunny with depth: the arrow pops out of the screen",
    "magica_olho": "The magic inside",
    "magica_h2": "Every picture becomes a layered world.",
    "hist1": "<b>An ordinary picture.</b> Flat, like any video on your screen.",
    "hist2": "<b>Pop3D sees the distance</b> of every point, from the character's nose to the farthest tree.",
    "hist3": "<b>It splits the scene into layers</b> and imagines what was hidden behind each one.",
    "hist4": "<b>It rebuilds everything in 3D</b>, one picture for each eye. Your brain does the rest.",
    "alt_historia": "Scene from Big Buck Bunny split into depth layers",
    "num1_v": "Free", "num1_t": "No ads, no subscription, no catch.",
    "num2_v": "Instant", "num2_t": "Press play and it's already 3D. No converting videos.",
    "num3_v": "Yours", "num3_t": "Your videos never leave your computer.",
    "tudo_olho": "Not just movies",
    "tudo_h2": "If it's on your PC, it's in 3D.",
    "tudo_intro": "Movies are just the beginning. Trips, family moments, photos, YouTube videos and even your favorite game gain depth.",
    "c_filme": "Movies & shows", "c_filme_p": "Your whole collection in 3D, on a cinema screen all your own.",
    "c_jogo": "Games", "c_jogo_p": "Your PC games in 3D in your headset, no mods needed.",
    "c_viagem": "Travel", "c_viagem_p": "Go back to that beach. This time, with depth.",
    "c_familia": "Family", "c_familia_p": "Birthdays, graduations, the baby's first steps.",
    "c_fotos": "Photos", "c_fotos_p": "Open a photo on your PC and step inside it.",
    "c_youtube": "YouTube & browser", "c_youtube_p": "Vlogs, documentaries, music videos: whatever is on your computer screen.",
    "c_natureza": "Nature", "c_natureza_p": "Landscapes with the depth they really have.",
    "dif_olho": "See the difference",
    "dif_h2": "Same picture. A whole new dimension.",
    "dif_intro": "Drag the line. On one side, the same old flat screen. On the other, the same scene with Pop3D. In your headset it's even more impressive: each eye gets its own image.",
    "dif_esq": "Regular screen", "dif_dir": "With Pop3D", "dif_alt": "Comparison between the flat image and the image with depth",
    "onde_olho": "Works with what you already have",
    "onde_h2": "Your way, on your headset.",
    "onde_intro": "Use our Quest app, the easiest way, or the PC VR app you already use.",
    "quest_selo": "Recommended", "quest_h3": "Pop3D app for Meta Quest",
    "quest_p": "Open the app on your headset and it finds your computer by itself over your home Wi-Fi. No cables, no setup.",
    "quest_l1": "Wireless, over Wi-Fi", "quest_l2": "Finds your PC by itself", "quest_l3": "Menus made for VR", "quest_l4": "Free",
    "botao_quest": "Meta Quest app", "detalhe_pc": "Windows 10 / 11 · NVIDIA RTX · Free",
    "em_breve_loja": "Coming soon to the Meta Horizon Store", "quest_ja": "Install it now in developer mode",
    "baixar_olho": "Download", "baixar_h2": "Up and running in minutes.",
    "baixar_intro": "Pop3D does the magic on your computer and shows it on your headset. Install it on your PC first; the Quest app is the easiest way to watch.",
    "etapa_pc": "On your computer", "pc_h3": "Pop3D for Windows",
    "pc_p": "Download, click Next and you're done. It gets ready for your graphics card by itself and keeps itself up to date.",
    "obrigado": "<b>Your download has started.</b> Open <b>Pop3D_Instalador.exe</b>. If Windows says “Windows protected your PC”, click <b>More info</b>, then <b>Run anyway</b>.",
    "etapa_quest": "On your Meta Quest",
    "dev_intro": "Until the app reaches the store, you can already install it over a USB cable:",
    "dev1": "On your phone, open the <b>Meta Horizon</b> app and turn on <b>Developer Mode</b> under Devices › Headset settings. Meta asks for a developer account, which is free.",
    "dev2": "Connect your Quest to your computer with a USB cable.",
    "dev3": "In Pop3D on your computer, open <b>Settings › Headset</b>, click <b>Install on Quest</b> and tap <b>Allow</b> inside the headset. Done!",
    "dev_apk": "Already use SideQuest? Download the APK",
    "outros_h3": "Also works with",
    "outros_p": "Prefer what you already use? Pop3D works with the most popular ways to connect a headset to a PC.",
    "steamvr_p": "Valve Index, HTC Vive, Pico and more",
    "req_h2": "What you need",
    "req_intro": "A computer with an NVIDIA RTX graphics card and a VR headset. That's it.",
    "req_sistema": "System", "req_placa": "Graphics card", "req_espaco": "Free space", "req_espaco_nota": "The app takes about 9 GB; the rest is room to install.", "req_oculos": "Headset",
    "req_oculos_v": "Meta Quest 2, 3, 3S or Pro, or a PC VR headset (SteamVR)",
    "duvidas_h2": "FAQ",
    "faq": [
        ("Is it really free?", "Yes. No ads, no subscription, no catch."),
        ("Do I need to convert my videos first?", "No. Just press play: the 3D happens while you watch."),
        ("Do I need to install anything on my headset?", "It's optional. The Pop3D app for Quest is the easiest way: it's coming soon to the Meta store, and you can already <a href=\"#baixar-quest\">install it in developer mode</a>. If you prefer, Pop3D also works with Steam Link, Air Link, Virtual Desktop and SteamVR."),
        ("I only installed the Quest app. Now what?", "The Quest app shows what Pop3D on your computer prepares. Also install <a href=\"#baixar\">Pop3D on your Windows PC</a>: with both open, the headset finds the computer by itself."),
        ("Is the installation quick?", "The first time, Pop3D downloads about 4 GB: that's the artificial intelligence that makes the magic happen, and it gets tuned for your graphics card. How long it takes depends on your internet. After that, the app opens in seconds and updates itself."),
        ("Does it work with streaming?", "It works with whatever shows up on your computer screen, like YouTube and most websites. Some paid services protect their videos against copying and don't let any program capture the picture. Videos on your computer work right away."),
        ("Does it work without an NVIDIA card?", "For now, the magic needs an NVIDIA RTX graphics card. If your PC doesn't have one, the installer tells you right at the start, before downloading anything."),
        ("Do my videos ever leave my computer?", "Never. It all happens on your computer, and the video goes straight to your headset over your home network. Pop3D only sends anonymous usage statistics to keep getting better, and you can turn that off in Settings. See the <a href=\"{{url_privacidade}}\">Privacy Policy</a>."),
        ("Windows said “Windows protected your PC”. What now?", "That's Windows' standard warning for new programs Microsoft doesn't know yet. Click <b>More info</b>, then <b>Run anyway</b>."),
        ("I have an idea for Pop3D!", "Awesome! Inside the app, under <b>Ideas &amp; feedback</b>, you can send it straight to us. Pop3D is brand new and grows with the people who use it."),
    ],
    "final_h2": "Ready to see everything in <span class=\"grad\">3D</span>?",
    "final_p": "Free. Installs itself. Works on your headset.",
    "privacidade": "Privacy Policy", "versoes": "All versions", "problema": "Found a problem? Tell us",
    "creditos_tit": "Image credits",
    "js": {"em_breve": "Coming soon", "forno": "The first version is almost out of the oven.", "versao": "Version",
           "no_pc": "Download it on your computer (Windows): Pop3D runs on your PC."},
}

ES = {
    "html_lang": "es",
    "titulo": "Pop3D: todo lo que ves, ahora en 3D en tu visor VR",
    "descricao": "Películas, series, viajes, fotos de la familia, YouTube y juegos: Pop3D convierte todo lo que pasa en tu computadora en 3D de verdad en tu visor VR. Gratis.",
    "nav_magica": "La magia", "nav_onde": "Dónde funciona", "nav_duvidas": "Preguntas", "nav_baixar": "Descargar gratis",
    "selo": "<b>Gratis</b> · Meta Quest y visores de PC",
    "h1": "Todo lo que ves,<br><span class=\"grad\">ahora en 3D.</span>",
    "lead": "Películas, series, el viaje del año pasado, el cumpleaños de la familia, YouTube, tus juegos. Pop3D convierte todo lo que pasa en tu computadora en 3D de verdad, directo en tu visor VR. Al instante, sin convertir nada.",
    "baixar": "Descargar gratis para Windows", "ver_magica": "Ver la magia",
    "rotulo_heroi": "Big Buck Bunny · Blender Foundation",
    "alt_heroi": "Escena de Big Buck Bunny con profundidad: la flecha sale de la pantalla",
    "magica_olho": "La magia por dentro",
    "magica_h2": "Cada imagen se vuelve un mundo en capas.",
    "hist1": "<b>Una imagen común.</b> Plana, como cualquier video en tu pantalla.",
    "hist2": "<b>Pop3D ve la distancia</b> de cada punto, desde el hocico del personaje hasta el último árbol.",
    "hist3": "<b>Separa la escena en capas</b> e imagina lo que estaba escondido detrás de cada una.",
    "hist4": "<b>Rearma todo en 3D</b>, una imagen para cada ojo. Tu cerebro hace el resto.",
    "alt_historia": "Escena de Big Buck Bunny separada en capas de profundidad",
    "num1_v": "Gratis", "num1_t": "Sin anuncios, sin suscripción y sin trampas.",
    "num2_v": "Al instante", "num2_t": "Le das play y ya está en 3D. Nada de convertir videos.",
    "num3_v": "Solo tuyo", "num3_t": "Tus videos nunca salen de tu computadora.",
    "tudo_olho": "No solo películas",
    "tudo_h2": "¿Pasa en tu PC? Se vuelve 3D.",
    "tudo_intro": "Las películas son solo el comienzo. Viajes, momentos en familia, fotos, videos de YouTube y hasta tu juego favorito ganan profundidad.",
    "c_filme": "Películas y series", "c_filme_p": "Toda tu colección en 3D, en una pantalla de cine solo para ti.",
    "c_jogo": "Juegos", "c_jogo_p": "Tus juegos de PC en 3D en el visor, sin instalar ningún mod.",
    "c_viagem": "Viajes", "c_viagem_p": "Vuelve a esa playa. Esta vez, con profundidad.",
    "c_familia": "Familia", "c_familia_p": "Cumpleaños, graduaciones, los primeros pasos del bebé.",
    "c_fotos": "Fotos", "c_fotos_p": "Abre una foto en la PC y entra en ella.",
    "c_youtube": "YouTube y navegador", "c_youtube_p": "Vlogs, documentales, videoclips: lo que esté en la pantalla de la computadora.",
    "c_natureza": "Naturaleza", "c_natureza_p": "Paisajes con la profundidad que tienen de verdad.",
    "dif_olho": "Mira la diferencia",
    "dif_h2": "La misma imagen. Otra dimensión.",
    "dif_intro": "Arrastra la línea. De un lado, la pantalla plana de siempre. Del otro, la misma escena con Pop3D. En el visor es todavía más impresionante: cada ojo recibe su propia imagen.",
    "dif_esq": "Pantalla común", "dif_dir": "Con Pop3D", "dif_alt": "Comparación entre la imagen plana y la imagen con profundidad",
    "onde_olho": "Funciona con lo que ya tienes",
    "onde_h2": "A tu manera, en tu visor.",
    "onde_intro": "Usa nuestra app para Quest, la forma más fácil, o la app de PC VR que ya usas.",
    "quest_selo": "Recomendado", "quest_h3": "App Pop3D para Meta Quest",
    "quest_p": "Abre la app en el visor y encuentra tu computadora sola, por el Wi-Fi de tu casa. Sin cables y sin configurar nada.",
    "quest_l1": "Inalámbrico, por Wi-Fi", "quest_l2": "Encuentra la PC sola", "quest_l3": "Menús hechos para VR", "quest_l4": "Gratis",
    "botao_quest": "App para Meta Quest", "detalhe_pc": "Windows 10 / 11 · NVIDIA RTX · Gratis",
    "em_breve_loja": "Muy pronto en la Meta Horizon Store", "quest_ja": "Instálala ahora en modo desarrollador",
    "baixar_olho": "Descargar", "baixar_h2": "Empieza en pocos minutos.",
    "baixar_intro": "Pop3D hace la magia en la computadora y la muestra en tu visor. Instálalo primero en la PC; la app del Quest es la forma más fácil de mirar.",
    "etapa_pc": "En la computadora", "pc_h3": "Pop3D para Windows",
    "pc_p": "Descarga, haz clic en Siguiente y listo. Se prepara solo para tu tarjeta gráfica y después se actualiza solo.",
    "obrigado": "<b>La descarga comenzó.</b> Abre <b>Pop3D_Instalador.exe</b>. Si Windows dice “Windows protegió su PC”, haz clic en <b>Más información</b> y luego en <b>Ejecutar de todas formas</b>.",
    "etapa_quest": "En el Meta Quest",
    "dev_intro": "Mientras la app no llega a la tienda, ya puedes instalarla con un cable USB:",
    "dev1": "En el celular, abre la app <b>Meta Horizon</b> y activa el <b>Modo desarrollador</b> en Dispositivos › Ajustes del visor. Meta pide una cuenta de desarrollador, que es gratis.",
    "dev2": "Conecta el Quest a la computadora con un cable USB.",
    "dev3": "En Pop3D de la computadora, abre <b>Ajustes › Visor</b>, haz clic en <b>Instalar en el Quest</b> y toca <b>Permitir</b> dentro del visor. ¡Listo!",
    "dev_apk": "¿Ya usas SideQuest? Descarga el APK",
    "outros_h3": "También funciona con",
    "outros_p": "¿Prefieres lo que ya usas? Pop3D funciona con las formas más populares de conectar el visor a la PC.",
    "steamvr_p": "Valve Index, HTC Vive, Pico y más",
    "req_h2": "Lo que necesitas",
    "req_intro": "Una computadora con tarjeta gráfica NVIDIA RTX y un visor VR. Nada más.",
    "req_sistema": "Sistema", "req_placa": "Tarjeta gráfica", "req_espaco": "Espacio libre", "req_espaco_nota": "La app ocupa unos 9 GB; el resto es margen para instalar.", "req_oculos": "Visor",
    "req_oculos_v": "Meta Quest 2, 3, 3S o Pro, o un visor de PC (SteamVR)",
    "duvidas_h2": "Preguntas",
    "faq": [
        ("¿De verdad es gratis?", "Sí. Sin anuncios, sin suscripción y sin trampas."),
        ("¿Tengo que convertir los videos antes?", "No. Solo dale play: el 3D sucede mientras miras."),
        ("¿Tengo que instalar algo en el visor?", "No es obligatorio. La app Pop3D para Quest es la forma más fácil: llega muy pronto a la tienda de Meta, y ya puedes <a href=\"#baixar-quest\">instalarla en modo desarrollador</a>. Si prefieres, Pop3D también funciona con Steam Link, Air Link, Virtual Desktop y SteamVR."),
        ("Instalé solo la app en el Quest. ¿Y ahora?", "La app del Quest muestra lo que prepara Pop3D en la computadora. Instala también <a href=\"#baixar\">Pop3D en tu PC con Windows</a>: con los dos abiertos, el visor encuentra la computadora solo."),
        ("¿La instalación es rápida?", "La primera vez, Pop3D descarga unos 4 GB: es la inteligencia artificial que hace la magia, y queda lista para tu tarjeta gráfica. El tiempo depende de tu internet. Después, la app abre en segundos y se actualiza sola."),
        ("¿Funciona con streaming?", "Funciona con lo que aparece en la pantalla de tu computadora, como YouTube y la mayoría de los sitios. Algunos servicios de pago protegen el video contra copias y no dejan que ningún programa capture la imagen. Los videos de tu computadora funcionan directo."),
        ("¿Funciona sin tarjeta NVIDIA?", "Por ahora, la magia necesita una tarjeta gráfica NVIDIA RTX. Si tu PC no tiene una, el instalador te avisa al principio, antes de descargar nada."),
        ("¿Mis videos salen de mi computadora?", "Nunca. Todo pasa en tu computadora y el video va directo al visor por la red de tu casa. Pop3D solo envía estadísticas anónimas de uso para seguir mejorando, y puedes desactivarlo en Ajustes. Mira la <a href=\"{{url_privacidade}}\">Política de Privacidad</a>."),
        ("Windows dijo “Windows protegió su PC”. ¿Y ahora?", "Es el aviso estándar de Windows para programas nuevos que Microsoft todavía no conoce. Haz clic en <b>Más información</b> y luego en <b>Ejecutar de todas formas</b>."),
        ("¡Tengo una idea para Pop3D!", "¡Genial! Dentro de la app, en <b>Ideas y sugerencias</b>, nos la mandas directo. Pop3D es nuevito y crece junto a quienes lo usan."),
    ],
    "final_h2": "¿Listo para ver todo en <span class=\"grad\">3D</span>?",
    "final_p": "Gratis. Se instala solo. Funciona en tu visor.",
    "privacidade": "Política de Privacidad", "versoes": "Todas las versiones", "problema": "¿Encontraste un problema? Cuéntanos",
    "creditos_tit": "Créditos de las imágenes",
    "js": {"em_breve": "Muy pronto", "forno": "La primera versión está por salir del horno.", "versao": "Versión",
           "no_pc": "Descárgalo en la computadora (Windows): Pop3D funciona en la PC."},
}

IDIOMAS = {"pt": PT, "en": EN, "es": ES}
